cpu1 : 
	g++ -Iinclude -o measure1.out measure1.c;
	mv measure1.out build;
	g++ -Iinclude -o measure2.out measure2.c;
	mv measure2.out build;
	g++ -Iinclude -o procedure.o procedure.c;
	mv procedure.o build;
	g++ -Iinclude -o system.o system.c;
	mv system.o build;
	g++ -Iinclude -o create_process.o create_process.c;
	mv create_process.o build;
	g++ -pthread -Iinclude -o create_thread.o create_thread.c;
	mv create_thread.o build;
