cpu1 : 
	g++ -Iinclude -o measure1.out measure1.c;
	mv measure1.out build;
	g++ -Iinclude -o measure2.out measure2.c;
	mv measure2.out build;
	g++ -Iinclude -o procedure.o procedure.c;
	mv procedure.o build;
	g++ -Iinclude -o system.o system.c;
	mv system.o build;